spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true


spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
  username: cos
  password: cos1234
  driver-class-name: com.mysql.cj.jdbc.Driver


spring.security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google ? ??? ???? ??.
            client-id: 398583905997-fogr6e2n9edscmqqdmvgba4hjka8l9f5.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: ???
            client-secret: ???
            scope:
              - email
              - public_profile

          # ???? OAuth2.0 ?? ????? ???? provider ??? ????.
          # ????? ???, ?? ???? ??? ????.
          naver:
            client-id: ???
            client-secret: ???
            scope:
              - name
              - email
              - profile_image
            client-name: Naver # ????? ??? ?? ????? ???? ?????.
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json? response ???? ????.

